### ISSUE TITLE
[Suggestion] Text Anchor

### ISSUE THREAD

**Issue by ArtifactyNight** [DecentSoftware-eu/DecentHolograms#10]
Add option to change **text anchor** by default or per-hologram

example `config.yml`

```yml
defaults:
  # Available options: above / center / below
  # Default: above
  text-anchor: above
```

example command: `/dh h anchor {hologram} {option}`
