### ISSUE TITLE
Custom text animation skip last step in list

### ISSUE THREAD

**Issue by Andre601** [DecentSoftware-eu/DecentHolograms#130]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms
2. Create a custom Animation (Example below)
3. Apply custom animation to hologram
4. See issue.

Example file:
```yaml
speed: 5

pause: 0

steps:
- '&f█&7████'
- '&7█&f█&7███'
- '&7██&f█&7██'
- '&7███&f█&7█'
- '&7████&f█'
- '&7███&f█&7█'
- '&7██&f█&7██'
- '&7█&f█&7███'
- '&7█&f█&7███'
```

### Solution

My current guess is an issue with the `getCurrentStep` method in combination with the usage of `steps.size() - 1` in the CustomTextAnimation class.

https://github.com/DecentSoftware-eu/DecentHolograms/blob/fde9238175b9fd71e38c4fb855b9003bf5f888f3/src/main/java/eu/decentsoftware/holograms/api/animations/Animation.java#L28

https://github.com/DecentSoftware-eu/DecentHolograms/blob/fde9238175b9fd71e38c4fb855b9003bf5f888f3/src/main/java/eu/decentsoftware/holograms/api/animations/custom/CustomTextAnimation.java#L29

Perhaps the issue is related to some rounding issue?

### Server Version

This server is running Paper version git-Paper-519 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 936205b) You are 2 version(s) behind Download the new version at: https://papermc.io/downloads/paper Previous version: git-Paper-514 (MC: 1.19.4)

### Client Version

1.19.4 (Using Quilt Modloader and some optimization mods)

### Plugin Version

2.8.1

### Log

https://mclo.gs/ney3PLB
