### ISSUE TITLE
Divides by zero when creating a gradient.

### ISSUE THREAD

**Issue by arima0k** [DecentSoftware-eu/DecentHolograms#14]
It spams the console until player left the area.

> [23:51:23 WARN]: java.lang.ArithmeticException: / by zero
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.createGradient(IridiumColorAPI.java:206)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.color(IridiumColorAPI.java:115)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.patterns.GradientPattern.process(GradientPattern.java:28)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.process(IridiumColorAPI.java:66)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.Common.colorize(Common.java:34)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:289)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.updateAnimations(HologramLine.java:400)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$updateAnimations$6(Hologram.java:392)
> [23:51:23 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAnimations(Hologram.java:392)
> [23:51:23 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAnimationsAll(Hologram.java:398)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:216)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [23:51:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> [23:51:23 WARN]: java.lang.ArithmeticException: / by zero
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.createGradient(IridiumColorAPI.java:206)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.color(IridiumColorAPI.java:115)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.patterns.GradientPattern.process(GradientPattern.java:28)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.process(IridiumColorAPI.java:66)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.Common.colorize(Common.java:34)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:289)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.updateAnimations(HologramLine.java:400)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$updateAnimations$6(Hologram.java:392)
> [23:51:23 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAnimations(Hologram.java:392)
> [23:51:23 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAnimationsAll(Hologram.java:398)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:216)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [23:51:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> [23:51:23 WARN]: java.lang.ArithmeticException: / by zero
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.createGradient(IridiumColorAPI.java:206)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.color(IridiumColorAPI.java:115)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.patterns.GradientPattern.process(GradientPattern.java:28)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.color.IridiumColorAPI.process(IridiumColorAPI.java:66)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.Common.colorize(Common.java:34)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.getText(HologramLine.java:289)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.HologramLine.updateAnimations(HologramLine.java:400)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.lambda$updateAnimations$6(Hologram.java:392)
> [23:51:23 WARN]:        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAnimations(Hologram.java:392)
> [23:51:23 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.updateAnimationsAll(Hologram.java:398)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.holograms.Hologram.tick(Hologram.java:216)
> [23:51:23 WARN]:        at DecentHolograms-2.2.5.jar//eu.decentsoftware.holograms.api.utils.tick.Ticker.lambda$tick$1(Ticker.java:79)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [23:51:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [23:51:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> [23:51:25 WARN]: java.lang.ArithmeticException
> [23:51:25 WARN]: java.lang.ArithmeticException
> [23:51:25 WARN]: java.lang.ArithmeticException
> [23:51:28 WARN]: java.lang.ArithmeticException
> [23:51:28 WARN]: java.lang.ArithmeticException
> [23:51:28 WARN]: java.lang.ArithmeticException
> [23:51:30 WARN]: java.lang.ArithmeticException
> [23:51:30 WARN]: java.lang.ArithmeticException
> [23:51:30 WARN]: java.lang.ArithmeticException
> [23:51:33 WARN]: java.lang.ArithmeticException
> [23:51:33 WARN]: java.lang.ArithmeticException
> [23:51:33 WARN]: java.lang.ArithmeticException

**Comment by arima0k** [comment]
holograms

```
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: -90.0
down-origin: false
always-face-player: true
pages:
- lines:
  - content: <#F0FF00>ABEJITA<#F0FF00>
    height: 0.3
  - content: '#ENTITY:BEE'
    height: 0.7500000238418579
  actions: {}
  always-face-player: true
```

```
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: false
always-face-player: true
pages:
- lines:
  - content: <#001AFF>&lTABLERO<#001AFF>
    height: 0.3
  actions: {}
  always-face-player: true
```

```
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: false
always-face-player: true
pages:
- lines:
  - content: <#FF0000>&lENTRA A LA AVENTURA<#FF0000>
    height: 0.3
  - content: <#FFFF00>&lPISA AQUI<#FFFF00>
    height: 0.3
  - content: <#0FFF00>&l↓<#0FFF00>
    height: 0.3
  actions: {}
  always-face-player: true
```

```
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: false
always-face-player: true
pages:
- lines:
  - content: <#B4FF00><#ANIM:typewriter>BIENVENIDOS</#ANIM></#FFC300>
    height: 0.3
  actions: {}
  always-face-player: true
```
