### ISSUE TITLE
Loop support for hologram lines

### ISSUE THREAD

**Issue by green-threads** [DecentSoftware-eu/DecentHolograms#206]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I think it would be useful for avoiding a lot of repetition mainly when creating leaderboards.

### Feature

I would like to see loop support for hologram lines. What I mean by that is being able to create loops for same lines where  index variable could be used as placeholder. This would remove a lot of repetition when creating and editing leaderboard holograms.

If it's still not clear what I mean, this example should clarify that.
```yaml
pages:
- lines:
  - content: "TOP 10 RICHEST PLAYERS"
    height: 0.3
    
    loop:
      range: 1-10
      content: "{index}. %cmi_baltop_name_{index}% - %cmi_baltop_money_{index}%"
      height: 0.3
```

### Alternatives

Currently it is only possible to edit the hologram line by line.
