### ISSUE TITLE
Update interval ignored, seems to always update every tick

### ISSUE THREAD

**Issue by ajgeiss0702** [DecentSoftware-eu/DecentHolograms#41]
Using this hologram to test:

```yaml
location: world:-298.849:147.429:-157.192
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: false
pages:
- lines:
  - content: '%rng_random%'
    height: 0.3
  actions: {}
```

`update-interval: 20` seems to be ignored, and it seems to update every tick:
https://cdn.discordapp.com/attachments/854816829263314959/960590264072818718/filtered-D527317D-471E-4E3E-9638-23C48C1D49D0.mp4
([link to the message on discord so you dont have to download it from the link above](https://discord.com/channels/850844430830534696/854816829263314959/960590265654075422))

I'm running DecentHolograms version 2.3.1
